### PR TITLE
Space operations

### PR DESCRIPTION
**Pull request by marcbachmann**
@peyerluk 

```
ldm project:design:add --name timeline --version 0.1.0
ldm project:design:remove --name timeline --version 0.1.0
```

### CODE REVIEW

**Comment by gabrielhase** [comment]
@marcbachmann can you also open a PR on the documentation project that reflects these changes?

**Comment by gabrielhase** [comment]
> I currently have no assets.basePath in the design.json. We still need that, right?

IMO the `basePath` is very important. The frontend apps use it to build the full paths to the CSS files. Even if we move our server architecture to only one design server per Livingdocs server I don't think that the frontend apps should have to know anything about this. Think for example about a design server migration in the case of a native app. If you have to hardcode the `basePath` somewhere in the native app itself and migrate the design server then you have to time the migration with a new release through the App Store which is almost impossible. If on the other hand the native app reads the `basePath` from the JSON response as it is now we don't have any problems.

**Comment by peyerluk** [comment]
> I currently have no assets.basePath in the design.json. We still need that, right?

Yep. I say we'll keep it.

**Comment by peyerluk** [comment]
:+1:

**Pull request merged**
